# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from MyGraphicsView import MyGraphicsView

class Ui_Digital_Photogrammetry(object):
    def setupUi(self, Digital_Photogrammetry):
        Digital_Photogrammetry.setObjectName("Digital_Photogrammetry")
        Digital_Photogrammetry.resize(1442, 777)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Digital_Photogrammetry)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(Digital_Photogrammetry)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gv_left = MyGraphicsView()
        self.gv_left.setObjectName("gv_left")
        self.horizontalLayout.addWidget(self.gv_left)
        self.gv_right = MyGraphicsView()
        self.gv_right.setObjectName("gv_right")
        self.horizontalLayout.addWidget(self.gv_right)
        spacerItem1 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tools = QtWidgets.QWidget(self.widget)
        self.tools.setObjectName("tools")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tools)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tb = QtWidgets.QTableView(self.tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb.sizePolicy().hasHeightForWidth())
        self.tb.setSizePolicy(sizePolicy)
        # self.tb.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)
        # self.tb.verticalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)
        self.tb.verticalHeader().setDefaultSectionSize(20)
        self.tb.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tb.setObjectName("tb")
        self.verticalLayout.addWidget(self.tb)
        self.harris_btn = QtWidgets.QPushButton(self.tools)
        self.harris_btn.setObjectName("harris_btn")
        self.verticalLayout.addWidget(self.harris_btn)
        self.correlation_btn = QtWidgets.QPushButton(self.tools)
        self.correlation_btn.setObjectName("correlation_btn")
        self.verticalLayout.addWidget(self.correlation_btn)
        self.lst_btn = QtWidgets.QPushButton(self.tools)
        self.lst_btn.setObjectName("lst_btn")
        self.verticalLayout.addWidget(self.lst_btn)
        self.export_btn = QtWidgets.QPushButton(self.tools)
        self.export_btn.setObjectName("export_btn")
        self.verticalLayout.addWidget(self.export_btn)
        self.horizontalLayout.addWidget(self.tools)
        self.horizontalLayout_2.addWidget(self.widget)

        self.retranslateUi(Digital_Photogrammetry)
        QtCore.QMetaObject.connectSlotsByName(Digital_Photogrammetry)

    def retranslateUi(self, Digital_Photogrammetry):
        _translate = QtCore.QCoreApplication.translate
        Digital_Photogrammetry.setWindowTitle(_translate("Digital_Photogrammetry", "数字影像匹配"))
        self.harris_btn.setText(_translate("Digital_Photogrammetry", "Harris角点检测"))
        self.correlation_btn.setText(_translate("Digital_Photogrammetry", "相关系数匹配"))
        self.lst_btn.setText(_translate("Digital_Photogrammetry", "最小二乘匹配"))
        self.export_btn.setText(_translate("Digital_Photogrammetry", "导出同名点文件"))
